POST http://localhost:8080/register HTTP/1.1
content-type: application/json 
{"name": "bilalislam"}


{"cmd":"join", "id":"XVlBzgba"}
{"cmd":"join", "id":"CMRAjWwh"}

{"cmd": "guess", "id":"XVlBzgba", "room":"room1699210612327731000", "data":4}
{"cmd": "guess", "id":"CMRAjWwh", "room":"room1699210612327731000", "data":6}